from .FedAvg import FedAvg
from .FedDyn import FedDyn
from .A_FedPD_SAM import A_FedPD_SAM
from .A_FedPD import A_FedPD
from .FedSMOO import FedSMOO
from .FedSpeed import FedSpeed
from .FedVRA import FedVRA
from .FedTOGA import FedTOGA
from .FedDA2 import FedDA2